### ISSUE TITLE
1d comparison kde plots

### ISSUE THREAD

**Issue by pesummary** [jkanner/streamlit-pe-demo#1]
When having a play around with this app, I found that the comparison plots are using the default gaussian_kde. This means that when plotting kdes for `a_1`, there is a non-zero probability below 0 and above 1, areas which are forbidden. I therefore recommend using the `module=gw` keyword argument:

```python
fig = published_dict.plot(param1, type='hist', kde=True, module="gw")
```

The combination of specifying the `gw` module and `kde=True` means that `pesummary` will use the [pesummary.core.plots.bounded_1d_kde.bounded_1d_kde function](https://git.ligo.org/lscsoft/pesummary/-/blob/master/pesummary/core/plots/bounded_1d_kde.py#L43) with bounds as defined [here](https://git.ligo.org/lscsoft/pesummary/-/blob/master/pesummary/gw/plots/bounds.py#L19).

**Comment by pesummary** [comment]
An example is shown below:

```python
from pesummary.utils.samples_dict import MultiAnalysisSamplesDict
import numpy as np

data = MultiAnalysisSamplesDict({"label1": {"a_1": np.random.uniform(0, 1, 10000)}})
fig = data.plot("a_1", type="hist", kde=True)
fig.savefig("gaussian.png")
fig.close()
fig = data.plot("a_1", type="hist", kde=True, module="gw")
fig.savefig("bounded.png")
fig.close()
```

![gaussian](https://user-images.githubusercontent.com/66682335/103916168-03c6a080-5104-11eb-8285-5e2ab33494c9.png)
![bounded](https://user-images.githubusercontent.com/66682335/103916172-04f7cd80-5104-11eb-91b9-f428daab22ab.png)

**Comment by jkanner** [comment]
Thanks, Charlie.  I appreciate your help with this.

**Comment by jkanner** [comment]
@pesummary  I gave this a quick try, and it seems to throw errors.

`fig = published_dict.plot(param1, type='hist', kde=True, module="gw")`

gives:

`TypeError: _1d_comparison_histogram_plot() got an unexpected keyword argument 'latex_friendly'`

**Comment by pesummary** [comment]
Interesting. This could be a version issue. Do you know what version of pesummary you are running? The above worked for me with the current master branch.

**Comment by pesummary** [comment]
I have just run `git blame` and it looks like the kwarg `latex_friendly` was added to the `pesummary.core.plots.plot._1d_comparison_histogram_plot` function 1 month ago meaning that it should be included in the `v0.11.0` release (see [here](https://git.ligo.org/lscsoft/pesummary/-/blob/3882c1b4b0fb9bacda85da0bc519046116d69d94/pesummary/core/plots/plot.py#L587)).

**Comment by jkanner** [comment]
Thanks for the quick feedback.  I'm using

 `pesummary           0.9.1`

As a guess, I notice that the event names I'm using include an underscore _ , and somehow a a backslash gets added when displayed in the plot legend.  Since the error message is about 'latex friendly', I'm suspicious the underscore may be triggering this behavior.

**Comment by pesummary** [comment]
ahh yes. I added the `latex_friendly` kwarg because the latex rendering was failing when an `_` was present. It therefore adds the `\` to counteract this and means that latex can render the label correctly. I am surprised that you are seeing a `\` in the label name though. Perhaps this could be because you are using `v0.9.1` and I am using `v0.11.0`?

**Comment by jkanner** [comment]
OK.  Its easy enough to test with v0.11.0.  I'll give this a try sometime soon.  Thanks for the quick response!

**Comment by pesummary** [comment]
Thanks :) Please let me know if this issue persists :)

**Comment by jkanner** [comment]
Hmmm ....

Moving to `pesummary == 0.11.0` DOES let me use the GW module, and the plots are beautiful.  But, this change introduces 2 new issues:

* The X-axis range on the 1-D histograms do not capture the range of the posterior for both events.  As a guess, the x-axis range seems to capture well the first event, but does not adjust for additional events included in the MultiAnalysisSamplesDict.  I would call this a bug.

* The plots seem to take longer to produce with this version of pesummary.  The app takes a full minute to run on my laptop.  Maybe that's OK, but it does seem a change from the earlier version.  I'm curious if that is expected.

**Comment by pesummary** [comment]
> The X-axis range on the 1-D histograms do not capture the range of the posterior for both events. As a guess, the x-axis range seems to capture well the first event, but does not adjust for additional events included in the MultiAnalysisSamplesDict. I would call this a bug.

Sorry to hear about this. I will take a look into this this afternoon and see if I can fix this for you :)

> The plots seem to take longer to produce with this version of pesummary. The app takes a full minute to run on my laptop. Maybe that's OK, but it does seem a change from the earlier version. I'm curious if that is expected.

I think this is expected because you are using a `Bounded_1d_kde` rather than a `gaussian_kde` (and this does slow things down if there are a lot of posterior samples). I am surprised to hear that it is slowing you down that much though. I would have expected the `Bounded_1d_kde` to be factor of 2 or less times slower than `gaussian_kde`. I will take a look at the source code this afternoon and see if there is some way of further optimising this kde method :)

**Comment by jkanner** [comment]
Hi Charlie.  Thank you for looking into this.

I did some additional testing with the slow running issue.  It is interesting.  The change seems to be related to the time to produce the reverse triangle plot using different versions of pesummary.  I've noticed that seaborn also changes versions on this change.

`fig = published_dict.plot(ch_param, type='reverse_triangle', grid=False)`

With two sets of PE samples in the "published_dict", this plot seems to take around 10-15 seconds to produce with `pesummary==0.9.1` and 50-60 seconds to produce with `pesummary==0.11.0`.  I'm not sure if this slowdown between different versions of pesummary is expected.

**Comment by jkanner** [comment]
This sounds like a good suggestion, but for some reason, `pesummary==0.11.0` is too slow in making plots.  I'm going to close this ticket for now.  Happy to revisit in the future, especially if a future version of pesummary resolves the slow plotting issue.
